# fly.toml app configuration file generated for conneroh-com-dev on 2025-04-02T04:56:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'conneroh-com-dev'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512M'
  cpu_kind = 'shared'
  cpus = 1
