// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package master

type Post struct {
	ID          int64  `db:"id" json:"id"`
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Slug        string `db:"slug" json:"slug"`
	Content     string `db:"content" json:"content"`
	BannerUrl   string `db:"banner_url" json:"banner_url"`
	CreatedAt   int64  `db:"created_at" json:"created_at"`
	UpdatedAt   string `db:"updated_at" json:"updated_at"`
}

type PostProject struct {
	PostID    int64 `db:"post_id" json:"post_id"`
	ProjectID int64 `db:"project_id" json:"project_id"`
}

type PostTag struct {
	PostID int64 `db:"post_id" json:"post_id"`
	TagID  int64 `db:"tag_id" json:"tag_id"`
}

type Project struct {
	ID          int64  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Slug        string `db:"slug" json:"slug"`
	Description string `db:"description" json:"description"`
	CreatedAt   *int64 `db:"created_at" json:"created_at"`
	UpdatedAt   *int64 `db:"updated_at" json:"updated_at"`
}

type ProjectPost struct {
	ProjectID int64 `db:"project_id" json:"project_id"`
	PostID    int64 `db:"post_id" json:"post_id"`
}

type ProjectTag struct {
	ProjectID int64 `db:"project_id" json:"project_id"`
	TagID     int64 `db:"tag_id" json:"tag_id"`
}

type Tag struct {
	ID          int64  `db:"id" json:"id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	Slug        string `db:"slug" json:"slug"`
	Icon        string `db:"icon" json:"icon"`
	Classes     string `db:"classes" json:"classes"`
	CreatedAt   int64  `db:"created_at" json:"created_at"`
	UpdatedAt   int64  `db:"updated_at" json:"updated_at"`
}

type TagPost struct {
	TagID  int64 `db:"tag_id" json:"tag_id"`
	PostID int64 `db:"post_id" json:"post_id"`
}

type TagProject struct {
	TagID     int64 `db:"tag_id" json:"tag_id"`
	ProjectID int64 `db:"project_id" json:"project_id"`
}
