// Code generated by twerge. DO NOT EDIT.
package classes

import twerge "github.com/conneroisu/twerge"

func SetCache() {
	twerge.Default().Handler.SetCache(ClassMapStr)
}

var ClassMapStr = map[string]twerge.CacheValue{
	"-right-4 h-24 -bottom-4 rounded-full w-24 z-0 absolute bg-purple-600": twerge.CacheValue{
		Generated: "tw-99",
		Merged:    "-right-4 z-0 absolute -bottom-4 rounded-full w-24 bg-purple-600 h-24",
	},
	"absolute -left-8 top-6 w-4 h-4 bg-green-500 rounded-full border-4 border-gray-900": twerge.CacheValue{
		Generated: "tw-129",
		Merged:    "bg-green-500 rounded-full border-gray-900 -left-8 top-6 absolute w-4 h-4 border-4",
	},
	"absolute left-1/2 -translate-x-1/2 w-0.5 h-full bg-gradient-to-b from-green-500 via-green-400 to-transparent": twerge.CacheValue{
		Generated: "tw-111",
		Merged:    "absolute w-0.5 h-full bg-gradient-to-b via-green-400 left-1/2 -translate-x-1/2 from-green-500 to-transparent",
	},
	"absolute left-1/2 -translate-x-1/2 w-4 h-4 bg-green-500 rounded-full border-4 border-gray-900 z-10": twerge.CacheValue{
		Generated: "tw-115",
		Merged:    "absolute bg-green-500 border-4 z-10 left-1/2 h-4 w-4 -translate-x-1/2 border-gray-900 rounded-full",
	},
	"absolute left-4 w-0.5 h-full bg-gradient-to-b from-green-500 via-green-400 to-transparent": twerge.CacheValue{
		Generated: "tw-127",
		Merged:    "h-full bg-gradient-to-b from-green-500 via-green-400 to-transparent absolute left-4 w-0.5",
	},
	"absolute z-10 grid sm:grid-cols-2 md:grid-cols-3 gap-1": twerge.CacheValue{
		Generated: "tw-73",
		Merged:    "grid sm:grid-cols-2 md:grid-cols-3 gap-1 absolute z-10",
	},
	"animate-spin h-5 w-5": twerge.CacheValue{
		Generated: "tw-49",
		Merged:    "w-5 animate-spin h-5",
	},
	"bg-gradient-to-b from-gray-900 to-gray-800 py-20": twerge.CacheValue{
		Generated: "tw-85",
		Merged:    "bg-gradient-to-b from-gray-900 to-gray-800 py-20",
	},
	"bg-gray-700 w-12 text-gray-300 justify-center hover:bg-gray-800 transition-colors rounded-full h-12 items-center flex": twerge.CacheValue{
		Generated: "tw-144",
		Merged:    "w-12 items-center transition-colors flex bg-gray-700 h-12 text-gray-300 justify-center hover:bg-gray-800 rounded-full",
	},
	"bg-gray-800 border-t border-gray-700 py-12": twerge.CacheValue{
		Generated: "tw-150",
		Merged:    "bg-gray-800 border-t border-gray-700 py-12",
	},
	"bg-gray-800 p-8 rounded-lg space-y-6 shadow-md": twerge.CacheValue{
		Generated: "tw-146",
		Merged:    "rounded-lg shadow-md bg-gray-800 space-y-6 p-8",
	},
	"bg-gray-800 py-16": twerge.CacheValue{
		Generated: "tw-101",
		Merged:    "bg-gray-800 py-16",
	},
	"bg-gray-800 rounded-lg mb-8 overflow-hidden p-6 shadow-lg": twerge.CacheValue{
		Generated: "tw-2",
		Merged:    "bg-gray-800 mb-8 shadow-lg rounded-lg overflow-hidden p-6",
	},
	"bg-gray-800 rounded-lg p-4 shadow-lg hover:shadow-xl transition-all": twerge.CacheValue{
		Generated: "tw-131",
		Merged:    "bg-gray-800 shadow-lg hover:shadow-xl rounded-lg transition-all p-4",
	},
	"bg-gray-800 rounded-lg p-6 shadow-lg hover:shadow-xl transition-all hover:-translate-y-1": twerge.CacheValue{
		Generated: "tw-118",
		Merged:    "rounded-lg hover:shadow-xl p-6 hover:-translate-y-1 shadow-lg transition-all bg-gray-800",
	},
	"bg-gray-800 rounded-lg shadow-md overflow-hidden p-6": twerge.CacheValue{
		Generated: "tw-30",
		Merged:    "p-6 rounded-lg bg-gray-800 overflow-hidden shadow-md",
	},
	"bg-gray-800 transition-all flex transform hover:-translate-y-3 flex-col shadow-md rounded-lg hover:shadow-lg duration-300 overflow-hidden h-full cursor-pointer": twerge.CacheValue{
		Generated: "tw-65",
		Merged:    "transform rounded-lg transition-all h-full bg-gray-800 flex cursor-pointer flex-col hover:shadow-lg duration-300 overflow-hidden hover:-translate-y-3 shadow-md",
	},
	"bg-gray-800 transition-all flex transform hover:-translate-y-3 flex-col shadow-md rounded-lg hover:shadow-lg duration-300 overflow-hidden h-full": twerge.CacheValue{
		Generated: "tw-17",
		Merged:    "flex-col shadow-md rounded-lg duration-300 overflow-hidden bg-gray-800 hover:-translate-y-3 h-full transition-all transform hover:shadow-lg flex",
	},
	"bg-gray-900 flex flex-col min-h-screen": twerge.CacheValue{
		Generated: "tw-74",
		Merged:    "flex flex-col min-h-screen bg-gray-900",
	},
	"bg-gray-900 py-16": twerge.CacheValue{
		Generated: "tw-107",
		Merged:    "bg-gray-900 py-16",
	},
	"bg-gray-900 transition-all flex transform hover:-translate-y-3 flex-col shadow-md rounded-lg hover:shadow-lg duration-300 overflow-hidden cursor-pointer h-full": twerge.CacheValue{
		Generated: "tw-106",
		Merged:    "bg-gray-900 hover:shadow-lg flex rounded-lg overflow-hidden transform flex-col shadow-md duration-300 h-full cursor-pointer transition-all hover:-translate-y-3",
	},
	"bg-green-500 p-8 rounded-lg shadow-md text-center": twerge.CacheValue{
		Generated: "tw-174",
		Merged:    "shadow-md rounded-lg bg-green-500 p-8 text-center",
	},
	"bg-green-600 font-medium px-3 py-2 text-white rounded-md": twerge.CacheValue{
		Generated: "tw-68",
		Merged:    "bg-green-600 px-3 rounded-md font-medium py-2 text-white",
	},
	"bg-green-600 rounded-full p-4 w-16 h-16 flex items-center justify-center": twerge.CacheValue{
		Generated: "tw-176",
		Merged:    "p-4 w-16 justify-center bg-green-600 flex h-16 rounded-full items-center",
	},
	"block": twerge.CacheValue{
		Generated: "tw-130",
		Merged:    "block",
	},
	"border-b border-gray-700 mb-6": twerge.CacheValue{
		Generated: "tw-38",
		Merged:    "mb-6 border-b border-gray-700",
	},
	"border-gray-700 border-b p-3": twerge.CacheValue{
		Generated: "tw-44",
		Merged:    "border-gray-700 border-b p-3",
	},
	"border-gray-800 border-b": twerge.CacheValue{
		Generated: "tw-75",
		Merged:    "border-gray-800 border-b",
	},
	"container mx-auto lg:px-8 sm:px-6 px-4": twerge.CacheValue{
		Generated: "tw-76",
		Merged:    "lg:px-8 px-4 container sm:px-6 mx-auto",
	},
	"container mx-auto px-4": twerge.CacheValue{
		Generated: "tw-151",
		Merged:    "container mx-auto px-4",
	},
	"container px-4 mx-auto": twerge.CacheValue{
		Generated: "tw-86",
		Merged:    "container px-4 mx-auto",
	},
	"flex flex-col md:flex-row gap-4 justify-center": twerge.CacheValue{
		Generated: "tw-170",
		Merged:    "md:flex-row gap-4 justify-center flex flex-col",
	},
	"flex flex-col md:flex-row justify-between items-center": twerge.CacheValue{
		Generated: "tw-152",
		Merged:    "flex flex-col md:flex-row justify-between items-center",
	},
	"flex flex-wrap gap-4 justify-center": twerge.CacheValue{
		Generated: "tw-156",
		Merged:    "flex flex-wrap gap-4 justify-center",
	},
	"flex items-center justify-center mb-8": twerge.CacheValue{
		Generated: "tw-164",
		Merged:    "flex items-center justify-center mb-8",
	},
	"flex justify-center items-center mt-8 space-x-2": twerge.CacheValue{
		Generated: "tw-54",
		Merged:    "flex justify-center items-center mt-8 space-x-2",
	},
	"flex md:hidden space-x-2": twerge.CacheValue{
		Generated: "tw-57",
		Merged:    "flex md:hidden space-x-2",
	},
	"flex text-white justify-center inset-0 font-bold items-center absolute text-xl": twerge.CacheValue{
		Generated: "tw-97",
		Merged:    "text-white justify-center font-bold absolute flex items-center inset-0 text-xl",
	},
	"flex-col lg:flex-row items-center justify-between flex": twerge.CacheValue{
		Generated: "tw-87",
		Merged:    "flex-col lg:flex-row items-center justify-between flex",
	},
	"flex-grow flex p-6 flex-col": twerge.CacheValue{
		Generated: "tw-21",
		Merged:    "flex-grow flex-col flex p-6",
	},
	"flex-grow": twerge.CacheValue{
		Generated: "tw-84",
		Merged:    "flex-grow",
	},
	"flex-wrap gap-4 flex": twerge.CacheValue{
		Generated: "tw-92",
		Merged:    "gap-4 flex flex-wrap",
	},
	"font-bold text-white mb-4 text-4xl": twerge.CacheValue{
		Generated: "tw-4",
		Merged:    "font-bold text-white mb-4 text-4xl",
	},
	"font-medium border-gray-600 py-3 rounded-md px-6 text-gray-300 transition-colors hover:bg-gray-800 border": twerge.CacheValue{
		Generated: "tw-94",
		Merged:    "transition-colors hover:bg-gray-800 border py-3 font-medium px-6 border-gray-600 rounded-md text-gray-300",
	},
	"font-medium flex items-center text-green-400 hover:underline text-lg cursor-pointer": twerge.CacheValue{
		Generated: "tw-104",
		Merged:    "text-green-400 hover:underline text-lg cursor-pointer font-medium flex items-center",
	},
	"font-medium flex items-center text-green-400 hover:underline text-lg": twerge.CacheValue{
		Generated: "tw-137",
		Merged:    "font-medium flex items-center text-green-400 hover:underline text-lg",
	},
	"font-medium flex items-center text-green-400 hover:underline text-sm": twerge.CacheValue{
		Generated: "tw-32",
		Merged:    "items-center text-green-400 hover:underline text-sm font-medium flex",
	},
	"font-semibold text-white text-2xl": twerge.CacheValue{
		Generated: "tw-5",
		Merged:    "font-semibold text-white text-2xl",
	},
	"font-semibold text-white text-xl": twerge.CacheValue{
		Generated: "tw-63",
		Merged:    "text-xl font-semibold text-white",
	},
	"gap-6 grid grid-cols-1 md:grid-cols-2": twerge.CacheValue{
		Generated: "tw-29",
		Merged:    "gap-6 grid grid-cols-1 md:grid-cols-2",
	},
	"grid grid-cols-1 lg:grid-cols-2 gap-8": twerge.CacheValue{
		Generated: "tw-135",
		Merged:    "grid grid-cols-1 lg:grid-cols-2 gap-8",
	},
	"grid grid-cols-1 md:grid-cols-2 gap-4": twerge.CacheValue{
		Generated: "tw-16",
		Merged:    "grid grid-cols-1 md:grid-cols-2 gap-4",
	},
	"grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8": twerge.CacheValue{
		Generated: "tw-138",
		Merged:    "grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8",
	},
	"grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 grid pt-2": twerge.CacheValue{
		Generated: "tw-58",
		Merged:    "grid pt-2 grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6",
	},
	"grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 grid": twerge.CacheValue{
		Generated: "tw-105",
		Merged:    "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8",
	},
	"h-1 bg-green-500 mt-2 w-16": twerge.CacheValue{
		Generated: "tw-6",
		Merged:    "h-1 bg-green-500 mt-2 w-16",
	},
	"h-1 w-16 bg-red-500 mx-auto mb-6": twerge.CacheValue{
		Generated: "tw-168",
		Merged:    "h-1 w-16 bg-red-500 mx-auto mb-6",
	},
	"h-12 transition-colors justify-center rounded-full text-gray-300 bg-gray-700 flex w-12 items-center hover:bg-red-500": twerge.CacheValue{
		Generated: "tw-145",
		Merged:    "justify-center rounded-full bg-gray-700 h-12 transition-colors text-gray-300 flex items-center hover:bg-red-500 w-12",
	},
	"h-24 w-24 rounded-full bg-red-500 flex items-center justify-center": twerge.CacheValue{
		Generated: "tw-165",
		Merged:    "bg-red-500 items-center flex w-24 rounded-full justify-center h-24",
	},
	"h-8 w-8 text-white": twerge.CacheValue{
		Generated: "tw-177",
		Merged:    "h-8 w-8 text-white",
	},
	"h-full w-full": twerge.CacheValue{
		Generated: "tw-18",
		Merged:    "h-full w-full",
	},
	"hidden md:block": twerge.CacheValue{
		Generated: "tw-110",
		Merged:    "hidden md:block",
	},
	"hidden md:flex space-x-2": twerge.CacheValue{
		Generated: "tw-56",
		Merged:    "hidden md:flex space-x-2",
	},
	"hover:bg-green-400 w-12 rounded-full bg-gray-700 transition-colors flex text-gray-300 h-12 items-center justify-center": twerge.CacheValue{
		Generated: "tw-143",
		Merged:    "transition-colors items-center flex h-12 justify-center hover:bg-green-400 bg-gray-700 text-gray-300 w-12 rounded-full",
	},
	"hover:text-white cursor-pointer text-gray-300": twerge.CacheValue{
		Generated: "tw-81",
		Merged:    "hover:text-white cursor-pointer text-gray-300",
	},
	"hover:underline": twerge.CacheValue{
		Generated: "tw-91",
		Merged:    "hover:underline",
	},
	"htmx-indicator top-2.5 text-green-500 absolute right-3": twerge.CacheValue{
		Generated: "tw-48",
		Merged:    "htmx-indicator text-green-500 absolute right-3 top-2.5",
	},
	"inline-flex items-center justify-center px-6 py-3 border border-gray-700 rounded-md shadow-sm text-base font-medium text-gray-300 bg-gray-900 hover:bg-gray-700 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500": twerge.CacheValue{
		Generated: "tw-172",
		Merged:    "focus:outline-none focus:ring-gray-500 text-gray-300 inline-flex border-gray-700 font-medium justify-center text-base bg-gray-900 shadow-sm focus:ring-2 px-6 py-3 rounded-md items-center border hover:bg-gray-700 transition-colors focus:ring-offset-2",
	},
	"inline-flex items-center justify-center px-6 py-3 border border-transparent rounded-md shadow-sm text-base font-medium text-white bg-green-600 hover:bg-green-700 transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500": twerge.CacheValue{
		Generated: "tw-171",
		Merged:    "focus:outline-none focus:ring-2 shadow-sm focus:ring-offset-2 items-center inline-flex justify-center py-3 bg-green-600 focus:ring-green-500 px-6 border border-transparent text-white rounded-md text-base hover:bg-green-700 transition-colors font-medium",
	},
	"items-center flex pr-3": twerge.CacheValue{
		Generated: "tw-71",
		Merged:    "items-center flex pr-3",
	},
	"items-center flex": twerge.CacheValue{
		Generated: "tw-72",
		Merged:    "items-center flex",
	},
	"items-center justify-between mb-3 flex p-6": twerge.CacheValue{
		Generated: "tw-62",
		Merged:    "p-6 items-center justify-between mb-3 flex",
	},
	"items-center text-sm text-gray-400 mt-6 flex": twerge.CacheValue{
		Generated: "tw-12",
		Merged:    "flex items-center text-sm text-gray-400 mt-6",
	},
	"justify-between h-16 flex items-center": twerge.CacheValue{
		Generated: "tw-77",
		Merged:    "justify-between h-16 flex items-center",
	},
	"justify-between items-center mb-12 pr-4 flex flex-col md:flex-row": twerge.CacheValue{
		Generated: "tw-102",
		Merged:    "flex flex-col md:flex-row justify-between items-center mb-12 pr-4",
	},
	"justify-center gap-4 mb-8 flex flex-wrap": twerge.CacheValue{
		Generated: "tw-142",
		Merged:    "mb-8 flex flex-wrap justify-center gap-4",
	},
	"leading-relaxed whitespace-pre-line text-gray-300": twerge.CacheValue{
		Generated: "tw-8",
		Merged:    "text-gray-300 leading-relaxed whitespace-pre-line",
	},
	"lg:w-1/2 mb-10 lg:mb-0": twerge.CacheValue{
		Generated: "tw-88",
		Merged:    "lg:w-1/2 mb-10 lg:mb-0",
	},
	"lg:w-1/2 relative": twerge.CacheValue{
		Generated: "tw-95",
		Merged:    "lg:w-1/2 relative",
	},
	"max-w-md w-full bg-gray-800 rounded-lg shadow-lg overflow-hidden": twerge.CacheValue{
		Generated: "tw-163",
		Merged:    "overflow-hidden rounded-lg w-full max-w-md bg-gray-800 shadow-lg",
	},
	"max-w-none my-6 text-gray-300 leading-relaxed": twerge.CacheValue{
		Generated: "tw-13",
		Merged:    "leading-relaxed max-w-none my-6 text-gray-300",
	},
	"max-w-none": twerge.CacheValue{
		Generated: "tw-7",
		Merged:    "max-w-none",
	},
	"mb-1 block text-sm font-medium text-gray-300": twerge.CacheValue{
		Generated: "tw-147",
		Merged:    "mb-1 block text-sm font-medium text-gray-300",
	},
	"mb-12 text-center": twerge.CacheValue{
		Generated: "tw-35",
		Merged:    "mb-12 text-center",
	},
	"mb-3 text-xl hover:underline font-semibold text-white line-clamp-2": twerge.CacheValue{
		Generated: "tw-22",
		Merged:    "text-xl font-semibold mb-3 hover:underline text-white line-clamp-2",
	},
	"mb-4 grid-cols-2 grid flex-wrap gap-2": twerge.CacheValue{
		Generated: "tw-24",
		Merged:    "flex-wrap gap-2 mb-4 grid-cols-2 grid",
	},
	"mb-4 md:text-5xl text-4xl leading-tight font-bold lg:text-6xl text-white": twerge.CacheValue{
		Generated: "tw-89",
		Merged:    "mb-4 md:text-5xl text-4xl leading-tight font-bold lg:text-6xl text-white",
	},
	"mb-4 text-3xl font-bold text-white": twerge.CacheValue{
		Generated: "tw-103",
		Merged:    "mb-4 text-3xl font-bold text-white",
	},
	"mb-6 flex justify-center": twerge.CacheValue{
		Generated: "tw-175",
		Merged:    "flex justify-center mb-6",
	},
	"mb-6 md:mb-0": twerge.CacheValue{
		Generated: "tw-153",
		Merged:    "mb-6 md:mb-0",
	},
	"mb-8": twerge.CacheValue{
		Generated: "tw-9",
		Merged:    "mb-8",
	},
	"md:hidden": twerge.CacheValue{
		Generated: "tw-126",
		Merged:    "md:hidden",
	},
	"min-h-screen flex items-center justify-center bg-gray-900 px-4 py-12": twerge.CacheValue{
		Generated: "tw-162",
		Merged:    "min-h-screen items-center flex justify-center bg-gray-900 px-4 py-12",
	},
	"ml-1 h-4 w-4": twerge.CacheValue{
		Generated: "tw-33",
		Merged:    "ml-1 h-4 w-4",
	},
	"mt-12": twerge.CacheValue{
		Generated: "tw-28",
		Merged:    "mt-12",
	},
	"mt-2": twerge.CacheValue{
		Generated: "tw-52",
		Merged:    "mt-2",
	},
	"mt-3 flex flex-wrap gap-2 justify-end": twerge.CacheValue{
		Generated: "tw-122",
		Merged:    "flex flex-wrap gap-2 justify-end mt-3",
	},
	"mt-3 flex flex-wrap gap-2": twerge.CacheValue{
		Generated: "tw-123",
		Merged:    "mt-3 flex flex-wrap gap-2",
	},
	"mt-4 md:mt-0": twerge.CacheValue{
		Generated: "tw-160",
		Merged:    "mt-4 md:mt-0",
	},
	"mt-8 pt-8 border-t border-gray-700 flex flex-col md:flex-row justify-between items-center": twerge.CacheValue{
		Generated: "tw-158",
		Merged:    "flex md:flex-row pt-8 flex-col justify-between items-center mt-8 border-t border-gray-700",
	},
	"mt-8 text-sm text-gray-500 text-center": twerge.CacheValue{
		Generated: "tw-173",
		Merged:    "text-gray-500 text-center mt-8 text-sm",
	},
	"mx-auto rounded-full h-64 bg-blue-600 relative md:w-80 md:h-80 w-64 shadow-lg": twerge.CacheValue{
		Generated: "tw-96",
		Merged:    "relative w-64 mx-auto bg-blue-600 md:h-80 h-64 md:w-80 shadow-lg rounded-full",
	},
	"opacity-25": twerge.CacheValue{
		Generated: "tw-50",
		Merged:    "opacity-25",
	},
	"opacity-75": twerge.CacheValue{
		Generated: "tw-51",
		Merged:    "opacity-75",
	},
	"overflow-hidden bg-gray-800 transform rounded-lg transition-all hover:shadow-lg duration-300 shadow-md hover:-translate-y-1 cursor-pointer h-full": twerge.CacheValue{
		Generated: "tw-66",
		Merged:    "duration-300 hover:-translate-y-1 cursor-pointer bg-gray-800 transition-all h-full hover:shadow-lg shadow-md overflow-hidden transform rounded-lg",
	},
	"overflow-hidden bg-gray-900 transform rounded-lg transition-all hover:shadow-lg duration-300 shadow-md hover:-translate-y-1 cursor-pointer h-full": twerge.CacheValue{
		Generated: "tw-136",
		Merged:    "hover:shadow-lg hover:-translate-y-1 cursor-pointer shadow-md transition-all duration-300 h-full overflow-hidden bg-gray-900 transform rounded-lg",
	},
	"p-2 focus:outline-none sm:hidden hover:text-white hover:bg-gray-700 rounded-md text-gray-300 mr-2": twerge.CacheValue{
		Generated: "tw-78",
		Merged:    "rounded-md sm:hidden text-gray-300 p-2 hover:text-white focus:outline-none hover:bg-gray-700 mr-2",
	},
	"p-4 inline-block": twerge.CacheValue{
		Generated: "tw-36",
		Merged:    "p-4 inline-block",
	},
	"p-6 rounded-lg overflow-hidden bg-gray-800 shadow-md hover:shadow-lg duration-300 transform transition-all hover:-translate-y-1 cursor-pointer h-full": twerge.CacheValue{
		Generated: "tw-61",
		Merged:    "shadow-md hover:shadow-lg overflow-hidden duration-300 transition-all h-full hover:-translate-y-1 p-6 transform rounded-lg bg-gray-800 cursor-pointer",
	},
	"p-6 rounded-lg overflow-hidden bg-gray-800 shadow-md hover:shadow-lg duration-300 transform transition-all hover:-translate-y-1": twerge.CacheValue{
		Generated: "tw-139",
		Merged:    "bg-gray-800 shadow-md p-6 overflow-hidden transform transition-all hover:shadow-lg duration-300 hover:-translate-y-1 rounded-lg",
	},
	"p-6": twerge.CacheValue{
		Generated: "tw-67",
		Merged:    "p-6",
	},
	"pb-4 mb-4 border-b border-gray-700": twerge.CacheValue{
		Generated: "tw-3",
		Merged:    "border-gray-700 pb-4 mb-4 border-b",
	},
	"pb-4 space-y-1 sm:hidden pt-2": twerge.CacheValue{
		Generated: "tw-82",
		Merged:    "pb-4 space-y-1 sm:hidden pt-2",
	},
	"pt-8 mt-12 border-t border-gray-700": twerge.CacheValue{
		Generated: "tw-14",
		Merged:    "pt-8 mt-12 border-t border-gray-700",
	},
	"px-1 sm:text-base text-sm font-medium py-4 border-b-2": twerge.CacheValue{
		Generated: "tw-40",
		Merged:    "py-4 px-1 sm:text-base text-sm font-medium border-b-2",
	},
	"px-2 bottom-0 py-1 right-0 text-xs rounded-tl-md text-white absolute border-emerald-800 border-2 border-r-0 border-b-0": twerge.CacheValue{
		Generated: "tw-26",
		Merged:    "text-white border-b-0 py-1 text-xs absolute px-2 bottom-0 rounded-tl-md border-2 border-r-0 border-emerald-800 right-0",
	},
	"px-3 bg-gray-800 transition-colors rounded-md border py-2 border-gray-700 text-gray-300 hover:bg-gray-700 flex items-center": twerge.CacheValue{
		Generated: "tw-60",
		Merged:    "bg-gray-800 py-2 border-gray-700 px-3 hover:bg-gray-700 items-center border text-gray-300 flex transition-colors rounded-md",
	},
	"px-3 bg-gray-800 transition-colors rounded-md border py-2 border-gray-700 text-gray-300 hover:bg-gray-700 opacity-50 flex items-center": twerge.CacheValue{
		Generated: "tw-55",
		Merged:    "transition-colors py-2 text-gray-300 bg-gray-800 opacity-50 flex hover:bg-gray-700 items-center px-3 rounded-md border border-gray-700",
	},
	"px-3 bg-gray-800 transition-colors rounded-md border py-2 border-gray-700 text-gray-300 hover:bg-gray-700": twerge.CacheValue{
		Generated: "tw-59",
		Merged:    "text-gray-300 hover:bg-gray-700 bg-gray-800 rounded-md border px-3 py-2 border-gray-700 transition-colors",
	},
	"px-4 container mx-auto py-2": twerge.CacheValue{
		Generated: "tw-53",
		Merged:    "py-2 mx-auto px-4 container",
	},
	"px-4 container mx-auto py-8": twerge.CacheValue{
		Generated: "tw-34",
		Merged:    "px-4 py-8 container mx-auto",
	},
	"px-4 mx-auto py-8 max-w-5xl": twerge.CacheValue{
		Generated: "tw-0",
		Merged:    "mx-auto py-8 max-w-5xl px-4",
	},
	"py-2 bg-gray-700 focus:outline-none border-gray-600 w-full focus:ring-green-500 border px-4 text-white rounded-md focus:ring-2": twerge.CacheValue{
		Generated: "tw-148",
		Merged:    "text-white py-2 w-full rounded-md focus:ring-2 focus:outline-none border bg-gray-700 focus:ring-green-500 px-4 border-gray-600",
	},
	"py-3 text-gray-900 rounded-md hover:opacity-90 font-medium transition-opacity bg-white px-6": twerge.CacheValue{
		Generated: "tw-93",
		Merged:    "px-6 hover:opacity-90 bg-white text-gray-900 py-3 font-medium transition-opacity rounded-md",
	},
	"relative flex justify-end": twerge.CacheValue{
		Generated: "tw-114",
		Merged:    "flex justify-end relative",
	},
	"relative flex justify-start": twerge.CacheValue{
		Generated: "tw-113",
		Merged:    "relative flex justify-start",
	},
	"relative w-full": twerge.CacheValue{
		Generated: "tw-19",
		Merged:    "relative w-full",
	},
	"relative": twerge.CacheValue{
		Generated: "tw-45",
		Merged:    "relative",
	},
	"rounded-full bg-blue-600 relative mx-auto shadow-lg": twerge.CacheValue{
		Generated: "tw-98",
		Merged:    "bg-blue-600 relative shadow-lg mx-auto rounded-full",
	},
	"rounded-md font-medium text-white transition-colors focus:ring-offset-2 focus:ring-2 focus:ring-green-500 w-full hover:bg-green-700 bg-green-600 py-3 focus:outline-none px-6": twerge.CacheValue{
		Generated: "tw-149",
		Merged:    "transition-colors w-full bg-green-600 rounded-md font-medium py-3 focus:ring-offset-2 focus:ring-2 focus:ring-green-500 hover:bg-green-700 px-6 text-white focus:outline-none",
	},
	"rounded-sm h-8 justify-center items-center flex w-8": twerge.CacheValue{
		Generated: "tw-64",
		Merged:    "justify-center items-center flex w-8 rounded-sm h-8",
	},
	"space-x-8 flex": twerge.CacheValue{
		Generated: "tw-39",
		Merged:    "space-x-8 flex",
	},
	"space-x-8 hidden sm:flex items-center ml-8": twerge.CacheValue{
		Generated: "tw-80",
		Merged:    "space-x-8 hidden sm:flex items-center ml-8",
	},
	"space-y-12": twerge.CacheValue{
		Generated: "tw-112",
		Merged:    "space-y-12",
	},
	"space-y-8 pl-12": twerge.CacheValue{
		Generated: "tw-128",
		Merged:    "space-y-8 pl-12",
	},
	"text-2xl font-bold text-white mb-4": twerge.CacheValue{
		Generated: "tw-15",
		Merged:    "text-2xl font-bold text-white mb-4",
	},
	"text-3xl font-bold mb-6 text-white": twerge.CacheValue{
		Generated: "tw-43",
		Merged:    "mb-6 text-white text-3xl font-bold",
	},
	"text-3xl font-bold text-center text-white mb-4": twerge.CacheValue{
		Generated: "tw-167",
		Merged:    "text-center text-white mb-4 text-3xl font-bold",
	},
	"text-base text-gray-300 hover:bg-gray-700 hover:text-white pl-3 pr-4 block py-2 font-medium": twerge.CacheValue{
		Generated: "tw-83",
		Merged:    "text-gray-300 hover:bg-gray-700 hover:text-white pr-4 pl-3 block py-2 font-medium text-base",
	},
	"text-center max-w-2xl mx-auto": twerge.CacheValue{
		Generated: "tw-140",
		Merged:    "mx-auto text-center max-w-2xl",
	},
	"text-center mb-12": twerge.CacheValue{
		Generated: "tw-108",
		Merged:    "text-center mb-12",
	},
	"text-gray-300 max-w-2xl mx-auto": twerge.CacheValue{
		Generated: "tw-109",
		Merged:    "max-w-2xl mx-auto text-gray-300",
	},
	"text-gray-300 mb-4 line-clamp-2": twerge.CacheValue{
		Generated: "tw-23",
		Merged:    "mb-4 line-clamp-2 text-gray-300",
	},
	"text-gray-300 mb-8 text-center": twerge.CacheValue{
		Generated: "tw-169",
		Merged:    "text-center text-gray-300 mb-8",
	},
	"text-gray-300 mb-8": twerge.CacheValue{
		Generated: "tw-141",
		Merged:    "text-gray-300 mb-8",
	},
	"text-gray-300 text-sm line-clamp-2": twerge.CacheValue{
		Generated: "tw-134",
		Merged:    "text-gray-300 text-sm line-clamp-2",
	},
	"text-gray-300 text-sm line-clamp-3": twerge.CacheValue{
		Generated: "tw-121",
		Merged:    "line-clamp-3 text-gray-300 text-sm",
	},
	"text-gray-400 hover:text-gray-300 border-transparent": twerge.CacheValue{
		Generated: "tw-42",
		Merged:    "text-gray-400 hover:text-gray-300 border-transparent",
	},
	"text-gray-400 hover:text-green-400 transition-colors": twerge.CacheValue{
		Generated: "tw-157",
		Merged:    "text-gray-400 hover:text-green-400 transition-colors",
	},
	"text-gray-400 px-2 py-1": twerge.CacheValue{
		Generated: "tw-69",
		Merged:    "text-gray-400 px-2 py-1",
	},
	"text-gray-400 text-sm hover:underline hover:text-green-400 transition-colors duration-200 pr-2": twerge.CacheValue{
		Generated: "tw-11",
		Merged:    "hover:text-green-400 transition-colors duration-200 pr-2 text-gray-400 text-sm hover:underline",
	},
	"text-gray-400 text-sm pr-2": twerge.CacheValue{
		Generated: "tw-10",
		Merged:    "text-gray-400 text-sm pr-2",
	},
	"text-gray-400": twerge.CacheValue{
		Generated: "tw-155",
		Merged:    "text-gray-400",
	},
	"text-gray-500 absolute left-3 top-2.5": twerge.CacheValue{
		Generated: "tw-47",
		Merged:    "absolute left-3 top-2.5 text-gray-500",
	},
	"text-gray-500 hover:text-gray-300 text-sm mx-2 transition-colors": twerge.CacheValue{
		Generated: "tw-161",
		Merged:    "hover:text-gray-300 text-sm mx-2 transition-colors text-gray-500",
	},
	"text-gray-500 text-sm": twerge.CacheValue{
		Generated: "tw-159",
		Merged:    "text-gray-500 text-sm",
	},
	"text-green-500 border-green-500": twerge.CacheValue{
		Generated: "tw-41",
		Merged:    "text-green-500 border-green-500",
	},
	"text-lg font-bold text-white mb-2": twerge.CacheValue{
		Generated: "tw-133",
		Merged:    "text-white mb-2 text-lg font-bold",
	},
	"text-py-1 bottom-0 px-2 rounded-tr-md text-white left-0 absolute border-emerald-800 border-2 border-l-0 border-b-0": twerge.CacheValue{
		Generated: "tw-25",
		Merged:    "px-2 rounded-tr-md border-l-0 border-emerald-800 bottom-0 absolute border-2 border-b-0 text-white left-0",
	},
	"text-sm px-3 items-center hover:underline bg-emerald-800 w-full transition-colors py-1 hover:bg-emerald-600 h-8 rounded-sm justify-between font-medium text-emerald-300 hover:text-white flex flex-row": twerge.CacheValue{
		Generated: "tw-70",
		Merged:    "text-sm bg-emerald-800 transition-colors hover:bg-emerald-600 items-center h-8 text-emerald-300 justify-between flex w-full rounded-sm font-medium flex-row px-3 py-1 hover:underline hover:text-white",
	},
	"text-sm text-green-400 font-semibold mb-1": twerge.CacheValue{
		Generated: "tw-119",
		Merged:    "text-sm text-green-400 font-semibold mb-1",
	},
	"text-white cursor-pointer pr-4 text-xl font-bold": twerge.CacheValue{
		Generated: "tw-79",
		Merged:    "text-xl font-bold text-white cursor-pointer pr-4",
	},
	"text-white mb-6": twerge.CacheValue{
		Generated: "tw-178",
		Merged:    "text-white mb-6",
	},
	"text-white text-xl font-bold mb-2": twerge.CacheValue{
		Generated: "tw-154",
		Merged:    "text-white text-xl font-bold mb-2",
	},
	"text-white": twerge.CacheValue{
		Generated: "tw-166",
		Merged:    "text-white",
	},
	"text-xl font-bold text-white mb-2": twerge.CacheValue{
		Generated: "tw-120",
		Merged:    "font-bold text-white mb-2 text-xl",
	},
	"text-xl font-semibold text-white mb-2": twerge.CacheValue{
		Generated: "tw-31",
		Merged:    "text-white mb-2 text-xl font-semibold",
	},
	"text-xl text-gray-300 max-w-2xl mx-auto": twerge.CacheValue{
		Generated: "tw-37",
		Merged:    "text-xl text-gray-300 max-w-2xl mx-auto",
	},
	"text-xl text-gray-300 mb-8 max-w-md": twerge.CacheValue{
		Generated: "tw-90",
		Merged:    "text-xl text-gray-300 mb-8 max-w-md",
	},
	"text-xs bg-gray-700 text-gray-300 px-2 py-1 rounded hover:bg-green-600 hover:text-white transition-colors cursor-pointer inline-block": twerge.CacheValue{
		Generated: "tw-124",
		Merged:    "bg-gray-700 cursor-pointer hover:bg-green-600 hover:text-white px-2 py-1 inline-block transition-colors text-xs text-gray-300 rounded",
	},
	"text-xs text-gray-500": twerge.CacheValue{
		Generated: "tw-125",
		Merged:    "text-xs text-gray-500",
	},
	"text-xs text-green-400 font-semibold mb-1": twerge.CacheValue{
		Generated: "tw-132",
		Merged:    "mb-1 text-xs text-green-400 font-semibold",
	},
	"w-5/12 ml-auto": twerge.CacheValue{
		Generated: "tw-117",
		Merged:    "w-5/12 ml-auto",
	},
	"w-5/12 mr-auto text-right": twerge.CacheValue{
		Generated: "tw-116",
		Merged:    "w-5/12 mr-auto text-right",
	},
	"w-full focus:outline-none border rounded-md pr-4 py-2 pl-10 bg-gray-700 text-white focus:ring-2 border-gray-600 focus:ring-green-500": twerge.CacheValue{
		Generated: "tw-46",
		Merged:    "bg-gray-700 w-full focus:outline-none rounded-md focus:ring-2 border-gray-600 pr-4 border pl-10 focus:ring-green-500 py-2 text-white",
	},
	"w-full h-48 object-cover": twerge.CacheValue{
		Generated: "tw-20",
		Merged:    "object-cover w-full h-48",
	},
	"w-full md:h-96 object-center rounded-lg object-cover shadow-md mb-8 h-64 bg-gray-800": twerge.CacheValue{
		Generated: "tw-27",
		Merged:    "mb-8 md:h-96 object-center shadow-md w-full rounded-lg object-cover bg-gray-800 h-64",
	},
	"w-full md:h-96 rounded-lg object-cover shadow-md mb-8 h-64": twerge.CacheValue{
		Generated: "tw-1",
		Merged:    "rounded-lg w-full md:h-96 object-cover shadow-md mb-8 h-64",
	},
	"z-0 absolute h-16 bg-pink-600 -top-4 rounded-full -left-4 w-16": twerge.CacheValue{
		Generated: "tw-100",
		Merged:    "absolute z-0 -top-4 -left-4 h-16 bg-pink-600 rounded-full w-16",
	},
}
