# fly.toml app configuration file generated for ccms on 2025-10-28T17:27:16-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ccms'
primary_region = 'ord'

[build]
  image = 'directus/directus:11'

[http_service]
  internal_port = 8055
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
