on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at midnight
permissions:
  contents: write
  actions: write
jobs:
  update-deps:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Update go.sum
        run: |
          nix run .#generate-templates
          nix run .#goSumUpdate
      - name: Commit flake.lock
        run: |
          nix flake update --commit-lock-file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update flake.lock
          title: Update flake.lock and go.sum for ${{ github.ref }}
          body: Update flake.lock and go.sum for ${{ github.ref }}
          branch: flake-lock-update-${{ github.ref }}
          delete-branch: true
