name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  actions: write
  packages: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Set up Cachix
        uses: cachix/cachix-action@ad2ddac53f961de1989924296a1f236fcfbaa4fc # v15
        with:
          name: conneroisu
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community, devenv

      - name: Build Package
        run: nix build --accept-flake-config .#C-conneroh -L

      - name: Deploy to Fly.io
        run: |
          echo "Deploying to Fly.io..."
          nix run --accept-flake-config .#deployPackage
        env:
          FLY_AUTH_TOKEN: ${{ secrets.FLY_AUTH_TOKEN }}
